<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->delete();
        $data_arr = array(
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'United States of America'],
            ['code' => 'AED', 'Symbol' => 'د.إ', 'digital_code' => '784', 'name' => 'UAE Dirham', 'country' => 'United Arab Emirates (UAE)'],
            ['code' => 'PKR', 'Symbol' => '₨', 'digital_code' => '586', 'name' => 'Pakistan Rupee', 'country' => 'Pakistan'],
            ['code' => 'INR', 'Symbol' => '₹', 'digital_code' => '356', 'name' => 'Indian Rupee', 'country' => 'Bhutan'],
            ['code' => 'INR', 'Symbol' => '₹', 'digital_code' => '356', 'name' => 'Indian Rupee', 'country' => 'India'],
            ['code' => 'AFN', 'Symbol' => 'Af', 'digital_code' => '971', 'name' => 'Afghani', 'country' => 'Afghanistan'],
            ['code' => 'ALL', 'Symbol' => 'L', 'digital_code' => '008', 'name' => 'Lek', 'country' => 'Albania'],
            ['code' => 'AMD', 'Symbol' => 'Դ', 'digital_code' => '051', 'name' => 'Armenian Dram', 'country' => 'Armenia'],
            ['code' => 'AOA', 'Symbol' => 'Kz', 'digital_code' => '973', 'name' => 'Kwanza', 'country' => 'Angola'],
            ['code' => 'ARS', 'Symbol' => '$', 'digital_code' => '032', 'name' => 'Argentine Peso', 'country' => 'Argentina'],
            ['code' => 'AUD', 'Symbol' => '$', 'digital_code' => '036', 'name' => 'Australian Dollar', 'country' => 'Australia'],
            ['code' => 'AUD', 'Symbol' => '$', 'digital_code' => '036', 'name' => 'Australian Dollar', 'country' => 'Kiribati'],
            ['code' => 'AUD', 'Symbol' => '$', 'digital_code' => '036', 'name' => 'Australian Dollar', 'country' => 'Coconut Islands'],
            ['code' => 'AUD', 'Symbol' => '$', 'digital_code' => '036', 'name' => 'Australian Dollar', 'country' => 'Nauru'],
            ['code' => 'AUD', 'Symbol' => '$', 'digital_code' => '036', 'name' => 'Australian Dollar', 'country' => 'Tuvalu'],
            ['code' => 'AWG', 'Symbol' => 'ƒ', 'digital_code' => '533', 'name' => 'Aruban Guilder/Florin', 'country' => 'Aruba'],
            ['code' => 'AZN', 'Symbol' => 'ман', 'digital_code' => '944', 'name' => 'Azerbaijanian Manat', 'country' => 'Azerbaijan'],
            ['code' => 'BAM', 'Symbol' => 'КМ', 'digital_code' => '977', 'name' => 'Konvertibilna Marka', 'country' => 'Bosnia and Herzegovina'],
            ['code' => 'BBD', 'Symbol' => '$', 'digital_code' => '052', 'name' => 'Barbados Dollar', 'country' => 'Barbados'],
            ['code' => 'BDT', 'Symbol' => '৳', 'digital_code' => '050', 'name' => 'Taka', 'country' => 'Bangladesh'],
            ['code' => 'BGN', 'Symbol' => 'лв', 'digital_code' => '975', 'name' => 'Bulgarian Lev', 'country' => 'Bulgaria'],
            ['code' => 'BHD', 'Symbol' => 'ب.د', 'digital_code' => '048', 'name' => 'Bahraini Dinar', 'country' => 'Bahrain'],
            ['code' => 'BIF', 'Symbol' => '₣', 'digital_code' => '108', 'name' => 'Burundi Franc', 'country' => 'Burundi'],
            ['code' => 'BMD', 'Symbol' => '$', 'digital_code' => '060', 'name' => 'Bermudian Dollar', 'country' => 'Bermuda'],
            ['code' => 'BND', 'Symbol' => '$', 'digital_code' => '096', 'name' => 'Brunei Dollar', 'country' => 'Brunei'],
            ['code' => 'BND', 'Symbol' => '$', 'digital_code' => '096', 'name' => 'Brunei Dollar', 'country' => 'Singapore'],
            ['code' => 'BOB', 'Symbol' => 'Bs.', 'digital_code' => '068', 'name' => 'Boliviano', 'country' => 'Bolivia'],
            ['code' => 'BRL', 'Symbol' => 'R$', 'digital_code' => '986', 'name' => 'Brazilian Real', 'country' => 'Brazil'],
            ['code' => 'BSD', 'Symbol' => '$', 'digital_code' => '044', 'name' => 'Bahamian Dollar', 'country' => 'Bahamas'],
            ['code' => 'BTN', 'Symbol' => '', 'digital_code' => '064', 'name' => 'Ngultrum', 'country' => 'Bhutan'],
            ['code' => 'BWP', 'Symbol' => 'P', 'digital_code' => '072', 'name' => 'Pula', 'country' => 'Botswana'],
            ['code' => 'BYN', 'Symbol' => 'Br', 'digital_code' => '933', 'name' => 'Belarusian Ruble', 'country' => 'Belarus'],
            ['code' => 'BZD', 'Symbol' => '$', 'digital_code' => '084', 'name' => 'Belize Dollar', 'country' => 'Belize'],
            ['code' => 'CAD', 'Symbol' => '$', 'digital_code' => '124', 'name' => 'Canadian Dollar', 'country' => 'Canada'],
            ['code' => 'CDF', 'Symbol' => '₣', 'digital_code' => '976', 'name' => 'Congolese Franc', 'country' => 'Congo (Kinshasa)'],
            ['code' => 'CHF', 'Symbol' => '₣', 'digital_code' => '756', 'name' => 'Swiss Franc', 'country' => 'Lichtenstein'],
            ['code' => 'CHF', 'Symbol' => '₣', 'digital_code' => '756', 'name' => 'Swiss Franc', 'country' => 'Switzerland'],
            ['code' => 'CLP', 'Symbol' => '$', 'digital_code' => '152', 'name' => 'Chilean Peso', 'country' => 'Chile'],
            ['code' => 'CNY', 'Symbol' => '¥', 'digital_code' => '156', 'name' => 'Yuan', 'country' => 'China'],
            ['code' => 'COP', 'Symbol' => '$', 'digital_code' => '170', 'name' => 'Colombian Peso', 'country' => 'Colombia'],
            ['code' => 'CRC', 'Symbol' => '₡', 'digital_code' => '188', 'name' => 'Costa Rican Colon', 'country' => 'Costa Rica'],
            ['code' => 'CUP', 'Symbol' => '$', 'digital_code' => '192', 'name' => 'Cuban Peso', 'country' => 'Cuba'],
            ['code' => 'CVE', 'Symbol' => '$', 'digital_code' => '132', 'name' => 'Cape Verde Escudo', 'country' => 'Cape Verde'],
            ['code' => 'CZK', 'Symbol' => 'Kč', 'digital_code' => '203', 'name' => 'Czech Koruna', 'country' => 'Czech Republic'],
            ['code' => 'DJF', 'Symbol' => '₣', 'digital_code' => '262', 'name' => 'Djibouti Franc', 'country' => 'Djibouti'],
            ['code' => 'DKK', 'Symbol' => 'kr', 'digital_code' => '208', 'name' => 'Danish Krone', 'country' => 'Denmark'],
            ['code' => 'DOP', 'Symbol' => '$', 'digital_code' => '214', 'name' => 'Dominican Peso', 'country' => 'Dominican Republic'],
            ['code' => 'DZD', 'Symbol' => 'د.ج', 'digital_code' => '012', 'name' => 'Algerian Dinar', 'country' => 'Algeria'],
            ['code' => 'EGP', 'Symbol' => '£', 'digital_code' => '818', 'name' => 'Egyptian Pound', 'country' => 'Egypt'],
            ['code' => 'ERN', 'Symbol' => 'Nfk', 'digital_code' => '232', 'name' => 'Nakfa', 'country' => 'Eritrea'],
            ['code' => 'ETB', 'Symbol' => '', 'digital_code' => '230', 'name' => 'Ethiopian Birr', 'country' => 'Ethiopia'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Akrotiri and Dhekelia'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Andorra'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Austria'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Belgium'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Cyprus'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Estonia'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Finland'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'France'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Germany'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Greece'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Ireland'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Italy'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Kosovo'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Latvia'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Lithuania'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Luxembourg'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Malta'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Monaco'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Montenegro'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Netherlands'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Portugal'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'San-Marino'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Slovakia'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Slovenia'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Spain'],
            ['code' => 'EUR', 'Symbol' => '€', 'digital_code' => '978', 'name' => 'Euro', 'country' => 'Vatican'],
            ['code' => 'FJD', 'Symbol' => '$', 'digital_code' => '242', 'name' => 'Fiji Dollar', 'country' => 'Fiji'],
            ['code' => 'FKP', 'Symbol' => '£', 'digital_code' => '238', 'name' => 'Falkland Islands Pound', 'country' => 'Falkland Islands'],
            ['code' => 'GBP', 'Symbol' => '£', 'digital_code' => '826', 'name' => 'Pound Sterling', 'country' => 'Alderney'],
            ['code' => 'GBP', 'Symbol' => '£', 'digital_code' => '826', 'name' => 'Pound Sterling', 'country' => 'British Indian Ocean Territory'],
            ['code' => 'GBP', 'Symbol' => '£', 'digital_code' => '826', 'name' => 'Pound Sterling', 'country' => 'Great Britain'],
            ['code' => 'GBP', 'Symbol' => '£', 'digital_code' => '826', 'name' => 'Pound Sterling', 'country' => 'Isle of Maine'],
            ['code' => 'GEL', 'Symbol' => 'ლ', 'digital_code' => '981', 'name' => 'Lari', 'country' => 'Georgia'],
            ['code' => 'GEL', 'Symbol' => 'ლ', 'digital_code' => '981', 'name' => 'Lari', 'country' => 'South Ossetia'],
            ['code' => 'GHS', 'Symbol' => '₵', 'digital_code' => '936', 'name' => 'Cedi', 'country' => 'Ghana'],
            ['code' => 'GIP', 'Symbol' => '£', 'digital_code' => '292', 'name' => 'Gibraltar Pound', 'country' => 'Gibraltar'],
            ['code' => 'GMD', 'Symbol' => 'D', 'digital_code' => '270', 'name' => 'Dalasi', 'country' => 'Gambia'],
            ['code' => 'GNF', 'Symbol' => '₣', 'digital_code' => '324', 'name' => 'Guinea Franc', 'country' => 'Guinea'],
            ['code' => 'GTQ', 'Symbol' => 'Q', 'digital_code' => '320', 'name' => 'Quetzal', 'country' => 'Guatemala'],
            ['code' => 'GYD', 'Symbol' => '$', 'digital_code' => '328', 'name' => 'Guyana Dollar', 'country' => 'Guyana'],
            ['code' => 'HKD', 'Symbol' => '$', 'digital_code' => '344', 'name' => 'Hong Kong Dollar', 'country' => 'Hong Kong'],
            ['code' => 'HNL', 'Symbol' => 'L', 'digital_code' => '340', 'name' => 'Lempira', 'country' => 'Honduras'],
            ['code' => 'HRK', 'Symbol' => 'Kn', 'digital_code' => '191', 'name' => 'Croatian Kuna', 'country' => 'Croatia'],
            ['code' => 'HTG', 'Symbol' => 'G', 'digital_code' => '332', 'name' => 'Gourde', 'country' => 'Haiti'],
            ['code' => 'HUF', 'Symbol' => 'Ft', 'digital_code' => '348', 'name' => 'Forint', 'country' => 'Hungary'],
            ['code' => 'IDR', 'Symbol' => 'Rp', 'digital_code' => '360', 'name' => 'Rupiah', 'country' => 'Indonesia'],
            ['code' => 'ILS', 'Symbol' => '₪', 'digital_code' => '376', 'name' => 'New Israeli Shekel', 'country' => 'Israel'],
            ['code' => 'ILS', 'Symbol' => '₪', 'digital_code' => '376', 'name' => 'New Israeli Shekel', 'country' => 'Palestine'],
            ['code' => 'IQD', 'Symbol' => 'ع.د', 'digital_code' => '368', 'name' => 'Iraqi Dinar', 'country' => 'Iraq'],
            ['code' => 'IRR', 'Symbol' => '﷼', 'digital_code' => '364', 'name' => 'Iranian Rial', 'country' => 'Iran'],
            ['code' => 'ISK', 'Symbol' => 'Kr', 'digital_code' => '352', 'name' => 'Iceland Krona', 'country' => 'Iceland'],
            ['code' => 'JMD', 'Symbol' => '$', 'digital_code' => '388', 'name' => 'Jamaican Dollar', 'country' => 'Jamaica'],
            ['code' => 'JOD', 'Symbol' => 'د.ا', 'digital_code' => '400', 'name' => 'Jordanian Dinar', 'country' => 'Jordan'],
            ['code' => 'JPY', 'Symbol' => '¥', 'digital_code' => '392', 'name' => 'Yen', 'country' => 'Japan'],
            ['code' => 'KES', 'Symbol' => 'Sh', 'digital_code' => '404', 'name' => 'Kenyan Shilling', 'country' => 'Kenya'],
            ['code' => 'KGS', 'Symbol' => '', 'digital_code' => '417', 'name' => 'Som', 'country' => 'Kyrgyzstan'],
            ['code' => 'KHR', 'Symbol' => '៛', 'digital_code' => '116', 'name' => 'Riel', 'country' => 'Cambodia'],
            ['code' => 'KPW', 'Symbol' => '₩', 'digital_code' => '408', 'name' => 'North Korean Won', 'country' => 'North Korea'],
            ['code' => 'KRW', 'Symbol' => '₩', 'digital_code' => '410', 'name' => 'South Korean Won', 'country' => 'South Korea'],
            ['code' => 'KWD', 'Symbol' => 'د.ك', 'digital_code' => '414', 'name' => 'Kuwaiti Dinar', 'country' => 'Kuwait'],
            ['code' => 'KYD', 'Symbol' => '$', 'digital_code' => '136', 'name' => 'Cayman Islands Dollar', 'country' => 'Cayman Islands'],
            ['code' => 'KZT', 'Symbol' => '〒', 'digital_code' => '398', 'name' => 'Tenge', 'country' => 'Kazakhstan'],
            ['code' => 'LAK', 'Symbol' => '₭', 'digital_code' => '418', 'name' => 'Kip', 'country' => 'Laos'],
            ['code' => 'LBP', 'Symbol' => 'ل.ل', 'digital_code' => '422', 'name' => 'Lebanese Pound', 'country' => 'Lebanon'],
            ['code' => 'LKR', 'Symbol' => 'Rs', 'digital_code' => '144', 'name' => 'Sri Lanka Rupee', 'country' => 'Sri Lanka'],
            ['code' => 'LRD', 'Symbol' => '$', 'digital_code' => '430', 'name' => 'Liberian Dollar', 'country' => 'Liberia'],
            ['code' => 'LSL', 'Symbol' => 'L', 'digital_code' => '426', 'name' => 'Loti', 'country' => 'Lesotho'],
            ['code' => 'LYD', 'Symbol' => 'ل.د', 'digital_code' => '434', 'name' => 'Libyan Dinar', 'country' => 'Libya'],
            ['code' => 'MAD', 'Symbol' => 'د.م.', 'digital_code' => '504', 'name' => 'Moroccan Dirham', 'country' => 'Morocco'],
            ['code' => 'MDL', 'Symbol' => 'L', 'digital_code' => '498', 'name' => 'Moldovan Leu', 'country' => 'Moldova'],
            ['code' => 'MGA', 'Symbol' => '', 'digital_code' => '969', 'name' => 'Malagasy Ariary', 'country' => 'Madagascar'],
            ['code' => 'MKD', 'Symbol' => 'ден', 'digital_code' => '807', 'name' => 'Denar', 'country' => 'Macedonia'],
            ['code' => 'MMK', 'Symbol' => 'K', 'digital_code' => '104', 'name' => 'Kyat', 'country' => 'Myanmar (Burma)'],
            ['code' => 'MNT', 'Symbol' => '₮', 'digital_code' => '496', 'name' => 'Tugrik', 'country' => 'Mongolia'],
            ['code' => 'MOP', 'Symbol' => 'P', 'digital_code' => '446', 'name' => 'Pataca', 'country' => 'Macao'],
            ['code' => 'MRU', 'Symbol' => 'UM', 'digital_code' => '929', 'name' => 'Ouguiya', 'country' => 'Mauritania'],
            ['code' => 'MUR', 'Symbol' => '₨', 'digital_code' => '480', 'name' => 'Mauritius Rupee', 'country' => 'Mauritius'],
            ['code' => 'MVR', 'Symbol' => 'ރ.', 'digital_code' => '462', 'name' => 'Rufiyaa', 'country' => 'Maldives'],
            ['code' => 'MWK', 'Symbol' => 'MK', 'digital_code' => '454', 'name' => 'Kwacha', 'country' => 'Malawi'],
            ['code' => 'MXN', 'Symbol' => '$', 'digital_code' => '484', 'name' => 'Mexican Peso', 'country' => 'Mexico'],
            ['code' => 'MYR', 'Symbol' => 'RM', 'digital_code' => '458', 'name' => 'Malaysian Ringgit', 'country' => 'Malaysia'],
            ['code' => 'MZN', 'Symbol' => 'MTn', 'digital_code' => '943', 'name' => 'Metical', 'country' => 'Mozambique'],
            ['code' => 'NAD', 'Symbol' => '$', 'digital_code' => '516', 'name' => 'Namibia Dollar', 'country' => 'Namibia'],
            ['code' => 'NGN', 'Symbol' => '₦', 'digital_code' => '566', 'name' => 'Naira', 'country' => 'Nigeria'],
            ['code' => 'NIO', 'Symbol' => 'C$', 'digital_code' => '558', 'name' => 'Cordoba Oro', 'country' => 'Nicaragua'],
            ['code' => 'NOK', 'Symbol' => 'kr', 'digital_code' => '578', 'name' => 'Norwegian Krone', 'country' => 'Norway'],
            ['code' => 'NPR', 'Symbol' => '₨', 'digital_code' => '524', 'name' => 'Nepalese Rupee', 'country' => 'Nepal'],
            ['code' => 'NZD', 'Symbol' => '$', 'digital_code' => '554', 'name' => 'New Zealand Dollar', 'country' => 'Cook Islands'],
            ['code' => 'NZD', 'Symbol' => '$', 'digital_code' => '554', 'name' => 'New Zealand Dollar', 'country' => 'New Zealand'],
            ['code' => 'NZD', 'Symbol' => '$', 'digital_code' => '554', 'name' => 'New Zealand Dollar', 'country' => 'Niue'],
            ['code' => 'NZD', 'Symbol' => '$', 'digital_code' => '554', 'name' => 'New Zealand Dollar', 'country' => 'Pitcairn Island'],
            ['code' => 'OMR', 'Symbol' => 'ر.ع.', 'digital_code' => '512', 'name' => 'Rial Omani', 'country' => 'Oman'],
            ['code' => 'PAB', 'Symbol' => 'B/.', 'digital_code' => '590', 'name' => 'Balboa', 'country' => 'Panama'],
            ['code' => 'PEN', 'Symbol' => 'S/.', 'digital_code' => '604', 'name' => 'Nuevo Sol', 'country' => 'Peru'],
            ['code' => 'PGK', 'Symbol' => 'K', 'digital_code' => '598', 'name' => 'Kina', 'country' => 'Papua New Guinea'],
            ['code' => 'PHP', 'Symbol' => '₱', 'digital_code' => '608', 'name' => 'Philippine Peso', 'country' => 'Philippines'],
            ['code' => 'PLN', 'Symbol' => 'zł', 'digital_code' => '985', 'name' => 'PZloty', 'country' => 'Poland'],
            ['code' => 'PYG', 'Symbol' => '₲', 'digital_code' => '600', 'name' => 'Guarani', 'country' => 'Paraguay'],
            ['code' => 'QAR', 'Symbol' => 'ر.ق', 'digital_code' => '634', 'name' => 'Qatari Rial', 'country' => 'Qatar'],
            ['code' => 'RON', 'Symbol' => 'L', 'digital_code' => '946', 'name' => 'Leu', 'country' => 'Romania'],
            ['code' => 'RSD', 'Symbol' => 'din', 'digital_code' => '941', 'name' => 'Serbian Dinar', 'country' => 'Kosovo'],
            ['code' => 'RSD', 'Symbol' => 'din', 'digital_code' => '941', 'name' => 'Serbian Dinar', 'country' => 'Serbia'],
            ['code' => 'RUB', 'Symbol' => 'р. ', 'digital_code' => '643', 'name' => 'Russian Ruble', 'country' => 'Russia'],
            ['code' => 'RUB', 'Symbol' => 'р. ', 'digital_code' => '643', 'name' => 'Russian Ruble', 'country' => 'South Ossetia'],
            ['code' => 'RWF', 'Symbol' => '₣', 'digital_code' => '646', 'name' => 'Rwanda Franc', 'country' => 'Rwanda'],
            ['code' => 'SAR', 'Symbol' => 'ر.س', 'digital_code' => '682', 'name' => 'Saudi Riyal', 'country' => 'Saudi Arabia'],
            ['code' => 'SBD', 'Symbol' => '$', 'digital_code' => '090', 'name' => 'Solomon Islands Dollar', 'country' => 'Solomon Islands'],
            ['code' => 'SCR', 'Symbol' => '₨', 'digital_code' => '690', 'name' => 'Seychelles Rupee', 'country' => 'Seychelles'],
            ['code' => 'SDG', 'Symbol' => '£', 'digital_code' => '938', 'name' => 'Sudanese Pound', 'country' => 'Sudan'],
            ['code' => 'SEK', 'Symbol' => 'kr', 'digital_code' => '752', 'name' => 'Swedish Krona', 'country' => 'Sweden'],
            ['code' => 'SGD', 'Symbol' => '$', 'digital_code' => '702', 'name' => 'Singapore Dollar', 'country' => 'Brunei'],
            ['code' => 'SGD', 'Symbol' => '$', 'digital_code' => '702', 'name' => 'Singapore Dollar', 'country' => 'Singapore'],
            ['code' => 'SHP', 'Symbol' => '£', 'digital_code' => '654', 'name' => 'Saint Helena Pound', 'country' => 'Ascension Island'],
            ['code' => 'SHP', 'Symbol' => '£', 'digital_code' => '654', 'name' => 'Saint Helena Pound', 'country' => 'Saint Helena'],
            ['code' => 'SHP', 'Symbol' => '£', 'digital_code' => '654', 'name' => 'Saint Helena Pound', 'country' => 'Tristan da Cunha'],
            ['code' => 'SLL', 'Symbol' => 'Le', 'digital_code' => '694', 'name' => 'Leone', 'country' => 'Sierra Leone'],
            ['code' => 'SOS', 'Symbol' => 'Sh', 'digital_code' => '706', 'name' => 'Somali Shilling', 'country' => 'Somalia'],
            ['code' => 'SRD', 'Symbol' => '$', 'digital_code' => '968', 'name' => 'Suriname Dollar', 'country' => 'Suriname'],
            ['code' => 'STN', 'Symbol' => 'Db', 'digital_code' => '930', 'name' => 'Dobra', 'country' => 'Sao Tome and Principe'],
            ['code' => 'SYP', 'Symbol' => 'ل.س', 'digital_code' => '760', 'name' => 'Syrian Pound', 'country' => 'Syria'],
            ['code' => 'SZL', 'Symbol' => 'L', 'digital_code' => '748', 'name' => 'Lilangeni', 'country' => 'Swaziland'],
            ['code' => 'THB', 'Symbol' => '฿', 'digital_code' => '764', 'name' => 'Baht', 'country' => 'Thailand'],
            ['code' => 'TJS', 'Symbol' => 'ЅМ', 'digital_code' => '972', 'name' => 'Somoni', 'country' => 'Tajikistan'],
            ['code' => 'TMT', 'Symbol' => 'm', 'digital_code' => '934', 'name' => 'Manat', 'country' => 'Turkmenistan'],
            ['code' => 'TND', 'Symbol' => 'د.ت', 'digital_code' => '788', 'name' => 'Tunisian Dinar', 'country' => 'Tunisia'],
            ['code' => 'TOP', 'Symbol' => 'T$', 'digital_code' => '776', 'name' => 'Pa’anga', 'country' => 'Tonga'],
            ['code' => 'TRY', 'Symbol' => '₤', 'digital_code' => '949', 'name' => 'Turkish Lira', 'country' => 'North Cyprus'],
            ['code' => 'TRY', 'Symbol' => '₤', 'digital_code' => '949', 'name' => 'Turkish Lira', 'country' => 'Turkey'],
            ['code' => 'TTD', 'Symbol' => '$', 'digital_code' => '780', 'name' => 'Trinidad and Tobago Dollar', 'country' => 'Trinidad and Tobago'],
            ['code' => 'TWD', 'Symbol' => '$', 'digital_code' => '901', 'name' => 'Taiwan Dollar', 'country' => 'Taiwan'],
            ['code' => 'TZS', 'Symbol' => 'Sh', 'digital_code' => '834', 'name' => 'Tanzanian Shilling', 'country' => 'Tanzania'],
            ['code' => 'UAH', 'Symbol' => '₴', 'digital_code' => '980', 'name' => 'Hryvnia', 'country' => 'Ukraine'],
            ['code' => 'UGX', 'Symbol' => 'Sh', 'digital_code' => '800', 'name' => 'Uganda Shilling', 'country' => 'Uganda'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'American Samoa'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'British Indian Ocean Territory'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'British Virgin Islands'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Guam'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Haiti'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Marshall Islands'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Micronesia'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Northern Mariana Islands'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Pacific Remote islands'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Palau'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Panama'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Puerto Rico'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'Turks and Caicos Islands'],
            ['code' => 'USD', 'Symbol' => '$', 'digital_code' => '840', 'name' => 'US Dollar', 'country' => 'US Virgin Islands'],
            ['code' => 'UYU', 'Symbol' => '$', 'digital_code' => '858', 'name' => 'Peso Uruguayo', 'country' => 'Uruguay'],
            ['code' => 'UZS', 'Symbol' => '', 'digital_code' => '860', 'name' => 'Uzbekistan Sum', 'country' => 'Uzbekistan'],
            ['code' => 'VEF', 'Symbol' => 'Bs F', 'digital_code' => '937', 'name' => 'Bolivar Fuerte', 'country' => 'Venezuela'],
            ['code' => 'VND', 'Symbol' => '₫', 'digital_code' => '704', 'name' => 'Dong', 'country' => 'Vietnam'],
            ['code' => 'VUV', 'Symbol' => 'Vt', 'digital_code' => '548', 'name' => 'Vatu', 'country' => 'Vanuatu'],
            ['code' => 'WST', 'Symbol' => 'T', 'digital_code' => '882', 'name' => 'Tala', 'country' => 'Samoa'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Benin'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Burkina Faso'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Cameroon'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Central African Republic'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Chad'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Congo (Brazzaville)'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'CFA Franc BCEAO'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Equatorial Guinea'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Gabon'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Guinea-Bissau'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Mali'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Niger'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Senegal'],
            ['code' => 'XAF', 'Symbol' => '₣', 'digital_code' => '950', 'name' => 'CFA Franc BCEAO', 'country' => 'Togo'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Anguilla'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Antigua and Barbuda'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Dominica'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Grenada'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Montserrat'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Saint Kitts and Nevis'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Saint Lucia'],
            ['code' => 'XCD', 'Symbol' => '$', 'digital_code' => '951', 'name' => 'East Caribbean Dollar', 'country' => 'Saint Vincent and Grenadine'],
            ['code' => 'XPF', 'Symbol' => '₣', 'digital_code' => '953', 'name' => 'CFP Franc', 'country' => 'French Polynesia'],
            ['code' => 'XPF', 'Symbol' => '₣', 'digital_code' => '953', 'name' => 'CFP Franc', 'country' => 'New Caledonia'],
            ['code' => 'XPF', 'Symbol' => '₣', 'digital_code' => '953', 'name' => 'CFP Franc', 'country' => 'Wallis and Futuna'],
            ['code' => 'YER', 'Symbol' => '﷼', 'digital_code' => '886', 'name' => 'Yemeni Rial', 'country' => 'Yemen'],
            ['code' => 'ZAR', 'Symbol' => 'R', 'digital_code' => '710', 'name' => 'Rand', 'country' => 'Lesotho'],
            ['code' => 'ZAR', 'Symbol' => 'R', 'digital_code' => '710', 'name' => 'Rand', 'country' => 'Namibia'],
            ['code' => 'ZAR', 'Symbol' => 'R', 'digital_code' => '710', 'name' => 'Rand', 'country' => 'South Africa'],
            ['code' => 'ZMW', 'Symbol' => 'ZK', 'digital_code' => '967', 'name' => 'Zambian Kwacha', 'country' => 'Zambia'],
            ['code' => 'ZWL', 'Symbol' => '$', 'digital_code' => '932', 'name' => 'Zimbabwe Dollar', 'country' => 'Zimbabwe'],
        );
        DB::table('currencies')->insert($data_arr);
    }
}
