<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GallerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            ['id'=>1, 'description'=>'Ready to taste the best food in Berlin? Satisfy your cravings for local food and culture with highlights along the way, together with a foodie host. Enjoy 10 delicious and typical tastings that range from sweet to savory as well as drinks on a tasty food tour in Berlin.', 'file_name1'=> 'Tours1-1.jpg', 'file_name2'=> 'Tours1-2.jpg', 'file_name3'=> 'Tours1-3.jpg', 'file_name4'=> 'Tours1-4.jpg', 'file_name5'=> 'Tours1-5.jpg', 'file_name6'=> 'Tours1-6.jpg', 'file_name7'=> 'Tours1-7.jpg', 'file_name8'=> 'Tours1-8.jpg', 'file_name9'=> 'Tours1-9.jpg', 'file_name10'=> 'Tours1-10.jpg', 'file_name11'=> 'Tours1-11.jpg', 'file_name12'=> 'Tours1-12.jpg', 'file_name13'=> 'Tours1-13.jpg', 'file_name14'=> 'Tours1-14.jpg', 'file_name15'=> 'Tours1-15.jpg', 'file_name16'=> 'Tours1-16.jpg', 'file_name17'=> 'Tours1-17.jpg', 'file_name18'=> 'Tours1-18.jpg', 'file_name19'=> 'NA', 'file_name20'=> 'NA',  'tour_id'=>1],        
            ['id'=>2, 'description'=>'Ready to taste the best food in Berlin? Satisfy your cravings for local food and culture with highlights along the way, together with a foodie host. Enjoy 10 delicious and typical tastings that range from sweet to savory as well as drinks on a tasty food tour in Berlin.', 'file_name1'=> 'Tours2-1.jpg', 'file_name2'=> 'Tours2-2.jpg', 'file_name3'=> 'Tours2-3.jpg', 'file_name4'=> 'Tours2-4.jpg', 'file_name5'=> 'Tours2-5.jpg', 'file_name6'=> 'Tours2-6.jpg', 'file_name7'=> 'Tours2-7.jpg', 'file_name8'=> 'Tours2-8.jpg', 'file_name9'=> 'Tours2-9.jpg', 'file_name10'=> 'Tours2-10.jpg', 'file_name11'=> 'Tours2-11.jpg', 'file_name12'=> 'Tours2-12.jpg', 'file_name13'=> 'Tours2-13.jpg', 'file_name14'=> 'Tours2-14.jpg', 'file_name15'=> 'NA', 'file_name16'=> 'NA', 'file_name17'=> 'NA', 'file_name18'=> 'NA', 'file_name19'=> 'NA', 'file_name20' => 'NA', 'tour_id'=>2],        
            ['id'=>3, 'description'=>'Want to see the best of Melbourne? We got you covered. But as you can expect from a Withlocals experience, the real excitement is its hidden gems. Join your favorite local and get a feeling of the city"s real vibe on a tour that has it all, so you can say: I experienced the real Melbourne!', 'file_name1'=> 'Tours3-1.jpg', 'file_name2'=> 'Tours3-2.jpg', 'file_name3'=> 'Tours3-3.jpg', 'file_name4'=> 'Tours3-4.jpg', 'file_name5'=> 'Tours3-5.jpg', 'file_name6'=> 'Tours3-6.jpg', 'file_name7'=> 'Tours3-7.jpg', 'file_name8'=> 'Tours3-8.jpg', 'file_name9'=> 'Tours3-9.jpg', 'file_name10'=> 'Tours3-10.jpg', 'file_name11'=> 'Tours3-11.jpg', 'file_name12'=> 'Tours3-12.jpg', 'file_name13'=> 'Tours3-13.jpg', 'file_name14'=> 'Tours3-14.jpg', 'file_name15'=> 'Tours3-15.jpg', 'file_name16'=> 'NA', 'file_name17' => 'NA', 'file_name18' => 'NA', 'file_name19' => 'NA', 'file_name20' => 'NA', 'tour_id'=>3],        
            ['id'=>4, 'description'=>'Take a walk off the beaten track, away from the tourist crowds, and see the real side of Melbourne. On this private tour, go beyond the classic route and explore Fitzroy where you’ll experience a different Melbourne, like a local with a local by your side!', 'file_name1'=> 'Tours4-1.jpg', 'file_name2'=> 'Tours4-2.jpg', 'file_name3'=> 'Tours4-3.jpg', 'file_name4'=> 'Tours4-4.jpg', 'file_name5'=> 'Tours4-5.jpg', 'file_name6'=> 'Tours4-6.jpg', 'file_name7'=> 'Tours4-7.jpg', 'file_name8'=> 'Tours4-8.jpg', 'file_name9'=> 'Tours4-9.jpg', 'file_name10'=> 'Tours4-10.jpg', 'file_name11'=> 'Tours4-11.jpg', 'file_name12'=> 'Tours4-12.jpg', 'file_name13'=> 'Tours4-13.jpg', 'file_name14'=> 'Tours4-14.jpg', 'file_name15'=> 'Tours4-15.jpg', 'file_name16' => 'NA', 'file_name17' => 'NA', 'file_name18' => 'NA', 'file_name19' => 'NA', 'file_name20' => 'NA', 'tour_id'=>4],        
            ['id'=>5, 'description'=>'Fall in love with the flavorful French cuisine on this delicious food tour in Paris! Enjoy a selection of 10 food and drink tastings hand-picked by your foodie local host, just for you. From yummy must-tries like a cheese board to unique dishes typical of the city such as crêpes; you’re in for a treat, so bring your appetite.

This culinary tour in Paris is a cultural journey that takes you further than the food you’ll eat. As you enjoy authentic local bites ranging from savory, sweet as well as drinks, you’ll also discover the city and its highlights. Stop to admire the Pletzl, Hotel de Ville de Paris, and Le Viaduc des Arts and hear about their local relevance from your host as you hop from one food hot spot to the other - what can be better than that?

Want to know what this food tour has in store for you? Your local foodie has you covered! And because sharing is caring, you and your group will get to try bites of famous dishes. Each of the hosts has carefully selected the tastings you’ll enjoy during this food tour. All of them passionate about food and their city, know the best spots to get the most authentic and typical bites. Pick your host according to your interests and you’ll be a part of a unique and flavorful experience catered to your taste buds.

Looking for a vegetarian alternative? It’s possible! The tour has been created with alternative tastings to fit your preferences. Just let your host know! The foodie locals are ready to take you on the best food tour in Paris. All you have to do is check out their profiles and pick your favorite local for a delicious culinary experience. This Paris food tour can be 100% personalized to match your diet and allergies.', 'file_name1'=> 'Tours5-1.jpg', 'file_name2'=> 'Tours5-2.jpg', 'file_name3'=> 'Tours5-3.jpg', 'file_name4'=> 'Tours5-4.jpg', 'file_name5'=> 'Tours5-5.jpg', 'file_name6'=> 'Tours5-6.jpg', 'file_name7'=> 'Tours5-7.jpg', 'file_name8'=> 'Tours5-8.jpg', 'file_name9'=> 'Tours5-9.jpg', 'file_name10'=> 'Tours5-10.jpg', 'file_name11'=> 'Tours5-11.jpg', 'file_name12'=> 'Tours5-12.jpg', 'file_name13' => 'NA', 'file_name14' => 'NA', 'file_name15' => 'NA', 'file_name16' => 'NA', 'file_name17' => 'NA', 'file_name18' => 'NA', 'file_name19' => 'NA', 'file_name20' => 'NA', 'tour_id'=>5],
            ['id'=>6, 'description'=>'Welcome to Paris! Want to know the best places to eat? Cool events in town? Which places to go to and which to avoid? Or simply get some help to navigate the city? Book this private tour with a local and get the perfect introduction to Paris to start your city trip on the right foot.', 'file_name1'=> 'Tours4-1.jpg', 'file_name2'=> 'Tours4-2.jpg', 'file_name3'=> 'Tours4-3.jpg', 'file_name4'=> 'Tours4-4.jpg', 'file_name5'=> 'Tours4-5.jpg', 'file_name6'=> 'Tours4-6.jpg', 'file_name7'=> 'Tours4-7.jpg', 'file_name8'=> 'Tours4-8.jpg', 'file_name9'=> 'Tours4-9.jpg', 'file_name10'=> 'Tours4-10.jpg', 'file_name11'=> 'Tours4-11.jpg', 'file_name12'=> 'Tours4-12.jpg', 'file_name13'=> 'Tours4-13.jpg', 'file_name14'=> 'Tours4-14.jpg', 'file_name15'=> 'Tours4-15.jpg', 'file_name16' => 'NA', 'file_name17' => 'NA', 'file_name18' => 'NA', 'file_name19' => 'NA', 'file_name20' => 'NA', 'tour_id'=>6],        

        );
        DB::table('galleries')->insert($data);
        
    }
}
